### ISSUE TITLE
Build - browserify fails, does not understand coffeescript

### ISSUE THREAD

**Issue by romanr** [NarrativeScience/log.io#112]
Anyone is able to build it? Tried on different systems, always fails with same error:

``` shell
log.io# cake browserify
Browserifying src/client.coffee to lib/log.io.js
SyntaxError: Line 2: Unexpected token ILLEGAL while parsing /home/logio/node_modules/log.io/src/client.coffee
```

It looks like browserify does not understand coffeescript? Is there something that needs to be installed to make it work?

**Comment by jonnor** [comment]
@msmathers I seem to be running into the same issue. On recent browserify specifying `-t coffeeify --extension=".coffee"` gives the parsing error. Specifying only `-t coffeeify` gives the loading error

However browserify 1.16.6 is lacking some wrappers needed by my code so that is unusable too... Any other know workaround

**Comment by nelsonomuto** [comment]
I ran into this issue as well, however running the cake build via npm run-script prepublish resolved it for me.
