### ISSUE TITLE
Browser performance issues when there are over 30,000 messages displayed.

### ISSUE THREAD

**Issue by jrthib** [NarrativeScience/log.io#139]
**Proposed fix:** Create a setting that rolls off older messages past a user specified limit.

**Comment by nelsonomuto** [comment]
I noticed this as well, we need a system that works for environments where 50 logs or more are generated per second

**Comment by nelsonomuto** [comment]
@msmathers Something that I noticed works quite well and improves performance is changing the client message_cap to a lower number. For example I changed it to 1 and it really boosted performance, the difference was night and day. 
Even at 200,000 messages there is no lag at all when the message_cap variable is reduced to 1!
As opposed to before with the previous cap at 5000 the page started crawling at ~ 20,000 messages and browser freezing at ~ 70,000 messages.

I analyzed the code and I don't see any use for having a larger message_cap, at least not in the current tag v0.3.4. My assumption is this is left over from a legacy feature. Otherwise, keeping the LogMessages backbone collection as small as possible tremendously improved the usability.  

client.coffee line 26 v0.3.4
# Cap LogMessages collection size
MESSAGE_CAP = 1

**Comment by nelsonomuto** [comment]
I also think using canvas for the UI as opposed to DOM Elements will greatly improve the performance.
The lag is still there with my fix, I noticed at around 400K messages that the browser starts slowing down considerably.

I will explore using canvas to render the UI.

**Comment by msmathers** [comment]
v0.4x is a complete rewrite of the UI component using React 16, and thus has a completely new rendering mechanism that is likely more performant than backbone.  No hard benchmarking has been done, so feel free to create any new issues around performance.
