### ISSUE TITLE
log.io do not respond from sshfs connected log-files

### ISSUE THREAD

**Issue by dimti** [NarrativeScience/log.io#182]
Hello

In my situation, i need use log.io from local computer, and parsing logs from a remote server connected via sshfs.

tail -f for remote filesystem works (but slowly) and a log.io not read this files (not send notification to server, if logs is changed). How to debug this situation and force log.io to work with network file systems?

**Comment by Soldia1138** [comment]
Can confirm this. 

On sshfs connected files, the harvester crawl does not trigger if changes are made from the remote machine.
However they do work on a manual `echo "test" >> mylog.log` on the local machine. During this, every change made on the remote machine is read as well.

Example:
Log-File `mylog.log` on remote machine, connected via sshfs to local machine, where the harvester is running.

Changes on remote machine: 
`echo "hello world from remote" >> mylog.log`
-> No output on log.io

Changes on local machine: 
`echo "hello world from local" >> mylog.log`

Output on log.io:
```
hello world from remote
hello world from local
```

I haven't found a way to debug it any further.

**Comment by msmathers** [comment]
log.io uses node.js' native `fs.watch()` to detect file changes, which uses `inotify` under the hood on linux system.  There are known issues around inotify support for network mounts: https://stackoverflow.com/q/4231243

This issue is happening below the application layer and likely won't be supported by log.io anytime soon.
